name: Build Superset Airgap Image

on:
workflow_dispatch:

jobs:
build:
runs-on: ubuntu-latest

```
steps:
  - name: Checkout repository
    uses: actions/checkout@v4

  - name: Build Docker image
    run: |
      docker build \
        -t localhost/secmon/superset:6.1.0-1 \
        .

  - name: Verify image
    run: |
      docker images

  - name: Export image
    run: |
      docker save localhost/secmon/superset:6.1.0-1 \
        -o secmon_superset-6.1.tar

  - name: Upload artifact
    uses: actions/upload-artifact@v4
    with:
      name: secmon_superset-6.1
      path: secmon_superset-6.1.tar
      retention-days: 7
